coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%
        if_no_uploads: error

    patch:
        default:
          target: 90%
          if_no_uploads: error

    changes: true
  ignore:
        - "src/main/java/com/flashcard/web/entities/*"
